window.texts = window.texts || {};

window.texts.nl = {
    'privatemode': 'Mode Privé',
    'news': 'Actualiteit',
    'recent_news': 'Recent',
    'agenda': 'Agenda',
    'parking_counter': 'Parking Counter',
    'parking_counter_url': 'https://parking.bnpparibasfortis.be/nl/',
    'luck': 'Doe mee',
    'luck_url': 'https://mp.bnpparibasfortis.com/dixit-contest/nl/',
    'work_title': 'Het nieuws uit jouw metier',
    'language': 'Taal',
    'push': 'Notificaties',
    'related': 'Gerelateerde artikels',
    'more_articles': 'Bekijk meer artikelen',
    'share': 'Share',
    'add_calendar': 'Voeg toe aan uw agenda',
    'the': '',
    'from': 'Van',
    'to': 'tot',
    'infos': 'Info',
    'in_the_news': 'In het nieuws',
    'search': 'Zoeken',
    'plz_connect': 'Gelieve uw internetverbinding na te kijken',
    'error': 'Er is een fout opgetreden.',
    'errorNames': 'Voorbeeld: voornaam.naam',
    'invalidData':'Les données ne sont pas valides',
    'titleLogin':'Vul hier jouw professioneel e-mailadres in',
    'validate':'Bevestigen',
    'cancel':'Annuleren',
    'titlePassword':'Vul hier jouw paswoord in',
    'subtitlePassword':'(via e-mail gekregen)',
    'notSend':'Heb je jouw paswoord niet gekregen?',
    'login':'Inloggen',
    'invalidEntry':'foutieve invoer',
    'invalidPassword':'ongeldig wachtwoord',
    'password':'wachtwoord',
    'titleSuccess':'My Dixit Today is geactiveerd',
    'backToArticles':'Terug naar artikelen',
    'noResults':'Geen resultaten',
    'sessionExpired':'Uw sessie is verlopen.',
    'aboutUs': 'Over ons',
    'aboutContent': 'Dixit Today is een officieel kanaal van BNP Paribas Fortis voor interne communicatie, te consulteren via de internetsite of de app en bedoeld voor alle medewerkers van BNP Paribas in België. Dixit Today informeert je dagelijks over de actualiteit van BNP Paribas Fortis en haar entiteiten. Dixit Today  licht de strategie van BNP Paribas Fortis toe en vertelt over wat er gebeurt binnen het bedrijf en zijn medewerkers.',
    'contactUs': 'Contact en suggesties',
    'about_us_url': 'https://dixit.bnpparibasfortis.be/nl/footer-pages/over-ons',
    'moreInfo': 'Meer weten ?',
    'errorComment': 'Vul alstublieft alle velden in',
    'confirmComment': 'Uw reactie wordt gevalideerd',
    'notification': 'Melding',
    'identification': 'Identificeer je als medewerker van BNP Paribas in België om toegang te krijgen tot alle artikels op Dixit Today',
    'loginButton': 'Identificeer je',
    'notRemind': 'Niet meer nodig'
}
