window.texts = window.texts || {};

window.texts.fr = {
    'privatemode': 'Mode Privé',
    'news': 'Actualités',
    'recent_news': 'Les articles récents',
    'agenda': 'Agenda',
    'parking_counter': 'Parking Counter',
    'parking_counter_url': 'https://parking.bnpparibasfortis.be/fr/',
    'luck': 'Tentez votre chance',
    'luck_url': 'https://mp.bnpparibasfortis.com/dixit-contest/fr/',
    'work_title': 'L\'actu de votre métier',
    'language': 'Langue',
    'push': 'Notifications',
    'related': 'Sur le même sujet',
    'more_articles': "Voir plus d'articles",
    'share': 'Partager',
    'add_calendar': 'Ajouter au calendrier',
    'the': 'Le',
    'from': 'Du',
    'to': 'au',
    'infos': 'Infos Pratiques',
    'in_the_news': 'À la une',
    'search': 'Recherche',
    'plz_connect': 'Veuillez vous connecter à internet.',
    'error': 'Une erreur s\est produite.',
    'errorNames': 'Exemple : prénom.nom',
    'invalidData':'Les données ne sont pas valides',
    'titleLogin':'Veuillez entrer votre adresse e-mail professionnelle',
    'validate':'Valider',
    'cancel':'Annuler',
    'titlePassword':'Veuillez entrer votre mot de passe',
    'subtitlePassword':'(reçu par email)',
    'notSend':'Vous n\'avez pas reçu votre mot de passe ?',
    'login':'S\'identifier',
    'invalidEntry':'entrée non valide',
    'invalidPassword':'mot de passe non valide',
    'password':'mot de passe',
    'titleSuccess':'My Dixit Today a été activé avec succès',
    'backToArticles':'Retour aux articles',
    'noResults':'Pas de résultats',
    'sessionExpired':'Votre session a expiré.',
    'aboutUs': 'Qui sommes-nous ?',
    'aboutContent': 'Dixit Today est un canal officiel de communication interne de BNP Paribas Fortis, consultable via un site internet ou une application, et qui s\’adresse à l\’ensemble des collaborateurs de BNP Paribas en Belgique. Dixit Today vous informe quotidiennement sur l\’actualité de BNP Paribas Fortis et de toutes ses entités. Dixit Today vous éclaire sur la stratégie de BNP Paribas Fortis et vous raconte la vie de l\’entreprise et de ses collaborateurs.',
    'contactUs': 'Contact et suggestions',
    'about_us_url': 'https://dixit.bnpparibasfortis.be/fr/footer-pages/qui-sommes-nous',
    'moreInfo': 'En savoir plus ?',
    'notification': 'Notification',
    'identification': 'Identifiez-vous en tant que collaborateur de BNP Paribas en Belgique pour accéder à tous les articles de Dixit Today',
    'loginButton': 'Identifiez-vous',
    'notRemind': 'Ne plus me demander'
}
